---
  - name: Gather Information from Azure VMs
    hosts: all  # Replace with the actual inventory group containing your Azure VMs
    become: true  # Run tasks with sudo
    tasks:
      - name: Gather OS Information
        ansible.builtin.debug:
          var: ansible_distribution

      - name: Gather Date
        ansible.builtin.debug:
          var: ansible_date_time.date
                     
      - name: Gather Running Services
        register: services
        ansible.builtin.debug:
          var: services.services

      - name: Gather Hardware Configuration (CPU and Memory)
        register: facts
        ansible.builtin.debug:
          var: facts.ansible_processor_vcpus
          var: facts.ansible_memtotal_mb
